# Resolve react_native_pods.rb with node to allow for hoisting
source 'https://cdn.cocoapods.org/'
source 'https://github.com/Nozbe/WatermelonDB.git'

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'DeRaat' do
  config = use_native_modules!

  # ⬇️  👇  THIS is the only line you need to add/replace  👇  ⬇️
 pod 'simdjson',
    path: '../node_modules/@nozbe/simdjson',
    modular_headers: true
  # (remove the previous simdjson line that pointed to the official repo)

  use_react_native!(
    :path     => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true  # uncomment if you use ccache
    )
  end
end
